// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsLend.DAL.Models;

public partial class EquipmentType
{
    public int TypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Equipment> Equipment { get; set; } = new List<Equipment>();
}