// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsLend.DAL.Models;

public partial class Equipment
{
    public int Id { get; set; }

    public string EquipmentId { get; set; }

    public string Name { get; set; }

    public string Brand { get; set; }

    public int TypeId { get; set; }

    public string Condition { get; set; }

    public decimal DailyFeeUsd { get; set; }

    public int InStock { get; set; }

    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();

    public virtual EquipmentType Type { get; set; }
}