// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsLend.DAL.Models;

public partial class Loan
{
    public int LoanId { get; set; }

    public int EquipmentId { get; set; }

    public int MemberId { get; set; }

    public DateOnly LoanDate { get; set; }

    public DateOnly DueDate { get; set; }

    public DateOnly? ReturnDate { get; set; }

    public decimal DailyFeeUsd { get; set; }

    public int CreatedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual Equipment Equipment { get; set; }

    public virtual Member Member { get; set; }
}