// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SportsLend.DAL.Models;

public partial class Member
{
    public int MemberId { get; set; }

    public string StudentId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}